import { Router } from "express";
import * as ctrl from "./menus.controller";
import { authenticate, authorize } from "../../middlewares/auth";
const router = Router();
router.use(authenticate);
router.use(authorize("SUPER_ADMIN", "ADMIN"));
router.get("/", ctrl.list);
router.get("/:id", ctrl.getById);
router.post("/", ctrl.create);
router.put("/:id", ctrl.update);
router.delete("/:id", ctrl.remove);
export default router;
